version: '3'
services:
  dotnet-app:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        VARIANT: "5.0"
    depends_on:
      - redis
    networks:
      - dapr-sample
  
  api-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "api",
     "-app-port", "5000",
     "-placement-host-address", "placement:50010",
     "-components-path", "/components"]
    volumes:
      - "./dapr-components/:/components"
    network_mode: "service:dotnet-app"
  
  userservice-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "userservice",
     "-app-port", "5001",
     "-placement-host-address", "placement:50010",
     "-components-path", "/components"]
    volumes:
      - "./dapr-components/:/components"
    network_mode: "service:dotnet-app"

  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50010"]
    ports:
      - "50010:50010"
    networks:
      - dapr-sample

  mysql:
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d:cached
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306
    networks:
      - dapr-sample

  redis:
    image: redis:latest
    environment:
      TZ: Asia/Tokyo
    ports:
      - 6379:6379
    command: ["redis-server"]
    networks:
      - dapr-sample

volumes:
  db-store:
networks:
    dapr-sample: