version: '3'
services:
  dotnet-app:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        VARIANT: "5.0"
    environment:
      DAPR_NETWORK: dapr-sample
    depends_on:
      - redis
      - dapr-placement
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity

  mysql:
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d:cached
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    environment:
      TZ: Asia/Tokyo
    ports:
      - 6379:6379
    command: ["redis-server"]

  dapr-placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50010", "--log-level", "debug"]
    ports:
      - "50010:50010"

volumes:
  db-store:
networks:
  default:
    name: dapr-sample
